#########################
## Sample Sass Lint File
#########################

# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
# Rule Configuration
rules:
  class-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: strictbem
  indentation:
    - 2
    -
      size: 4
